### ISSUE TITLE
Support older version of Symfony

### ISSUE THREAD

**Issue by cve** [chalasr/RCHJWTUserBundle#9]
Hi,

thanks for your awesome working.

I want to integrate that bundle with https://github.com/api-platform/api-platform and I see that your awesome bundle requires Symfony at ~3.0, but api platform requires Symfony ~2.7. So are there any possibilities how to integrate that with api platform?

**Comment by chalasr** [comment]
Hi @cve,

Glad to hear that this bundle fits your needs.

In fact, the master branch doesn't represent a stable release for now, the first release that will be drafted on will be `2.0` that is only in [alpha1](https://github.com/chalasr/RCHJWTUserBundle/releases/tag/v2.0.0-alpha1) ATM, requiring symfony `~3.0` as you pointed out.

The `1.x` branch requires symfony `~2.8` (`> 2.8` and `< 3.0.0`), so you should be able to integrate it with api-platform as well as in the symfony fullstack framework. using the `1.*` releases (the last stable one being [`v1.3.0`](https://github.com/chalasr/RCHJWTUserBundle/releases/tag/v1.3.0)).

The reason of why restrict symfony to `~3.0` in the `2.x` releases is simply _FOSUserBundle_ and its symfony compatibility that is restrictive, I'm trying to find the better compromise so nothing is very sure for now.

Hope you can use it in api-platform without problem, otherwise please feel free to open issues, I'll do my best!

Thank you.

**Comment by cve** [comment]
It works with api platform in version > 1.0 :), thanks for advices.
